pub mod addr;
pub mod addrv2;
pub mod block;
pub mod blockheader;
pub mod buffer;
pub mod deepclone;
pub mod getaddr;
pub mod getdata;
pub mod inv;
pub mod invvector;
pub mod magic;
pub mod netaddr;
pub mod packetheader;
pub mod packetpayload;
pub mod ping;
pub mod pong;
pub mod sendaddrv2;
pub mod sendheaders;
pub mod tx;
pub mod varint;
pub mod varstr;
pub mod verack;
pub mod version;

pub const MAX_PACKET_SIZE: usize = 4 * 1024 * 1024;
