name: Build (and later push) docker images for x86_64 and aarch64

on:
  push:
    branches: [ master, dev ]

jobs:
  build-and-push:
    strategy:
      matrix:
        system: [x86_64-linux]
    runs-on:
      - self-hosted
      - ${{ matrix.system == 'aarch64-linux' && 'ARM64' || 'x64' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31

      - name: Build Docker Image
        run: |
          nix build .#packages.${{matrix.system}}.dockerImage --out-link result-docker

      - name: Install fuse-overlayfs so podman works
        run: |
          sudo apt update && sudo apt install -y fuse-overlayfs

      - name: Login to registry
        env:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        run: |
          echo $password | podman login $registry --username $username --password-stdin

      - name: Load docker image
        run: |
          podman load --input result-docker

      - name: Tag and push
        run: |
          podman tag bitlens ${{ secrets.DOCKER_REGISTRY }}/bitlens-${{ github.ref_name }}:${{ github.sha }}-${{ matrix.system }}
          podman tag bitlens ${{ secrets.DOCKER_REGISTRY }}/bitlens-${{ github.ref_name }}:latest-${{ matrix.system }}
          # Push
          podman push ${{ secrets.DOCKER_REGISTRY }}/bitlens-${{ github.ref_name }}:${{ github.sha }}-${{ matrix.system }}
          podman push ${{ secrets.DOCKER_REGISTRY }}/bitlens-${{ github.ref_name }}:latest-${{ matrix.system }}


  publish-manifest:
    runs-on: 'self-hosted'
    needs: [build-and-push]
    steps:
      - name: Install fuse-overlayfs so podman works
        run: |
          sudo apt update && sudo apt install -y fuse-overlayfs

      - name: Login to registry
        env:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        run: |
          echo $password | podman login $registry --username $username --password-stdin

      - name: Create and push manifest
        run: |
          # For commit SHA tag
          podman manifest create ${{ secrets.DOCKER_REGISTRY }}/bitlens-${{ github.ref_name }}:${{ github.sha }} \
            #--amend ${{ secrets.DOCKER_REGISTRY }}/bitlens-${{ github.ref_name }}:${{ github.sha }}-aarch64-linux \
            --amend ${{ secrets.DOCKER_REGISTRY }}/bitlens-${{ github.ref_name }}:${{ github.sha }}-x86_64-linux
          podman manifest push ${{ secrets.DOCKER_REGISTRY }}/bitlens-${{ github.ref_name }}:${{ github.sha }}

          # For latest tag
          podman manifest create ${{ secrets.DOCKER_REGISTRY }}/bitlens-${{ github.ref_name }}:latest \
            #--amend ${{ secrets.DOCKER_REGISTRY }}/bitlens-${{ github.ref_name }}:latest-aarch64-linux \
            --amend ${{ secrets.DOCKER_REGISTRY }}/bitlens-${{ github.ref_name }}:latest-x86_64-linux
          podman manifest push ${{ secrets.DOCKER_REGISTRY }}/bitlens-${{ github.ref_name }}:latest
